ProjetoArtCouro/ProjetoArtCouro.Web/Controllers/Estoques/EstoqueController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ProjetoArtCouro.Model.Models.Estoque;
using ProjetoArtCouro.Resources.Resources;
using ProjetoArtCouro.Web.Infra.Authorization;
using ProjetoArtCouro.Web.Infra.Service;

namespace ProjetoArtCouro.Web.Controllers.Estoques
{
    public class EstoqueController : BaseController
    {
        public ActionResult PesquisaEstoque()
        {
            ViewBag.Title = Mensagens.Stock;
            ViewBag.SubTitle = Mensagens.StockSearch;
            return View();
        }

        [HttpPost]
        public JsonResult PesquisaEstoque(PesquisaEstoqueModel model)
        {
            var response = ServiceRequest.Post<List<EstoqueModel>>(model, "api/Estoque/PesquisarEstoque");
            if (response.Data.ObjetoRetorno != null && !response.Data.ObjetoRetorno.Any())
            {
                response.Data.Mensagem = Erros.NoAccountReceivableForTheGivenFilter;
            }
            return ReturnResponse(response);
        }
    }
}

ProjetoArtCouro/ProjetoArtCouro.Web/Controllers/Pessoas/ClienteController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ProjetoArtCouro.Model.Models.Cliente;
using ProjetoArtCouro.Model.Models.Common;
using ProjetoArtCouro.Resources.Resources;
using ProjetoArtCouro.Web.Infra.Authorization;
using ProjetoArtCouro.Web.Infra.Service;
using ProjetoArtCouro.Web.Models.Enums;

namespace ProjetoArtCouro.Web.Controllers.Pessoas
{
    public class ClienteController : BaseController
    {
        [CustomAuthorize(Roles = "PesquisaCliente")]
        public ActionResult PesquisaCliente()
        {
            ViewBag.Title = Mensagens.Client;
            ViewBag.SubTitle = Mensagens.SearchClient;
            return View();
        }

        [HttpPost]
        [CustomAuthorize(Roles = "PesquisaCliente")]
        public JsonResult PesquisaCliente(PesquisaClienteModel model)
        {
            var response = ServiceRequest.Post<List<ClienteModel>>(model, "api/Cliente/PesquisarCliente");
            if (response.Data.ObjetoRetorno != null && !response.Data.ObjetoRetorno.Any())
            {
                response.Data.Mensagem = Erros.NoClientForTheGivenFilter;
            }
            return ReturnResponse(response);
        }

        [CustomAuthorize(Roles = "NovoCliente")]
        public ActionResult NovoCliente()
        {
            CriarViewBags(Mensagens.NewClient);
            var listaBase = new List<LookupModel>();
            ViewBag.Enderecos = listaBase;
            ViewBag.Telefones = listaBase;
            ViewBag.Celulares = listaBase;
            ViewBag.Emails = listaBase;
            return View();
        }

        [HttpPost]
        [CustomAuthorize(Roles = "NovoCliente")]
        public JsonResult NovoCliente(ClienteModel model)
        {
            model.PapelPessoa = (int)TipoPapelPessoaEnum.Cliente;
            var response = ServiceRequest.Post<RetornoBase<object>>(model, "api/Cliente/CriarCliente");
            return ReturnResponse(response);
        }

        [CustomAuthorize(Roles = "EditarCliente")]
        public ActionResult EditarCliente(int codigoCliente)
        {
            CriarViewBags(Mensagens.EditClient);
            var response = ServiceRequest.Post<ClienteModel>(new { codigoCliente = codigoCliente }, "api/Cliente/PesquisarClientePorCodigo");
            var model = response.Data.ObjetoRetorno;
            if (model == null)
            {
                return View(response.Data.ObjetoRetorno);
            }

            var listaBase = new List<LookupModel>();
            ViewBag.Enderecos = model.Enderecos.Select(x => new LookupModel
            {
                Codigo = x.EnderecoId ?? 0,
                Nome = string.Format("Logradouro: {0}, N: {1}, Cidade: {2}, CEP: {3}", x.Logradouro, x.Numero, x.Cidade, x.Cep)
            }).ToList();
            ViewBag.Telefones = model.MeioComunicacao.Telefones ?? listaBase;
            ViewBag.Celulares = model.MeioComunicacao.Celulares ?? listaBase;
            ViewBag.Emails = model.MeioComunicacao.Emalis ?? listaBase;

            return View(response.Data.ObjetoRetorno);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "EditarCliente")]
        public JsonResult EditarCliente(ClienteModel model)
        {
            var response = ServiceRequest.Put<RetornoBase<object>>(model, "api/Cliente/EditarCliente");
            return ReturnResponse(response);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "ExcluirCliente")]
        public JsonResult ExcluirCliente(int codigoCliente)
        {
            var response = ServiceRequest.Delete<RetornoBase<object>>(new { codigoCliente = codigoCliente }, "api/Cliente/ExcluirCliente");
            return ReturnResponse(response);
        }

        private void CriarViewBags(string subTitle)
        {
            ViewBag.Title = Mensagens.Client;
            ViewBag.SubTitle = subTitle;

            var listaBase = new List<LookupModel>();
            var response = ServiceRequest.Get<List<LookupModel>>("api/Pessoa/ObterListaEstado");
            if (response.Data.TemErros)
            {
                ModelState.AddModelError("Erro", response.Data.Mensagem);
                ViewBag.Estados = listaBase;
            }
            ViewBag.Estados = response.Data.ObjetoRetorno;
            response = ServiceRequest.Get<List<LookupModel>>("api/Pessoa/ObterListaEstadoCivil");
            if (response.Data.TemErros)
            {
                ModelState.AddModelError("Erro", response.Data.Mensagem);
                ViewBag.EstadosCivis = listaBase;
            }
            ViewBag.EstadosCivis = response.Data.ObjetoRetorno;
        }
    }
}

ProjetoArtCouro/ProjetoArtCouro.Web/Controllers/Pessoas/FornecedorController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ProjetoArtCouro.Model.Models.Common;
using ProjetoArtCouro.Model.Models.Fornecedor;
using ProjetoArtCouro.Resources.Resources;
using ProjetoArtCouro.Web.Infra.Authorization;
using ProjetoArtCouro.Web.Infra.Service;
using ProjetoArtCouro.Web.Models.Enums;

namespace ProjetoArtCouro.Web.Controllers.Pessoas
{
    public class FornecedorController : BaseController
    {
        [CustomAuthorize(Roles = "PesquisaFornecedor")]
        public ActionResult PesquisaFornecedor()
        {
            ViewBag.Title = Mensagens.Provider;
            ViewBag.SubTitle = Mensagens.NewProvider;
            return View();
        }

        [HttpPost]
        [CustomAuthorize(Roles = "PesquisaFornecedor")]
        public JsonResult PesquisaFornecedor(PesquisaFornecedorModel model)
        {
            var response = ServiceRequest.Post<List<FornecedorModel>>(model, "api/Fornecedor/PesquisarFornecedor");
            if (response.Data.ObjetoRetorno != null && !response.Data.ObjetoRetorno.Any())
            {
                response.Data.Mensagem = Erros.NoProviderForTheGivenFilter;
            }
            return ReturnResponse(response);
        }

        [CustomAuthorize(Roles = "NovoFornecedor")]
        public ActionResult NovoFornecedor()
        {
            CriarViewBags(Mensagens.NewProvider);
            var listaBase = new List<LookupModel>();
            ViewBag.Enderecos = listaBase;
            ViewBag.Telefones = listaBase;
            ViewBag.Celulares = listaBase;
            ViewBag.Emails = listaBase; 
            return View();
        }

        [HttpPost]
        [CustomAuthorize(Roles = "NovoFornecedor")]
        public JsonResult NovoFornecedor(FornecedorModel model)
        {
            model.PapelPessoa = (int)TipoPapelPessoaEnum.Fornecedor;
            var response = ServiceRequest.Post<RetornoBase<object>>(model, "api/Fornecedor/CriarFornecedor");
            return ReturnResponse(response);
        }

        [CustomAuthorize(Roles = "EditarFornecedor")]
        public ActionResult EditarFornecedor(int codigoFornecedor)
        {
            CriarViewBags(Mensagens.EditProvider);
            var response = ServiceRequest.Post<FornecedorModel>(new { codigoFornecedor = codigoFornecedor }, "api/Fornecedor/PesquisarFornecedorPorCodigo");
            var model = response.Data.ObjetoRetorno;
            if (model == null)
            {
                return View(response.Data.ObjetoRetorno);
            }

            var listaBase = new List<LookupModel>();
            ViewBag.Enderecos = model.Enderecos.Select(x => new LookupModel
            {
                Codigo = x.EnderecoId ?? 0,
                Nome = string.Format("Logradouro: {0}, N: {1}, Cidade: {2}, CEP: {3}", x.Logradouro, x.Numero, x.Cidade, x.Cep)
            }).ToList();
            ViewBag.Telefones = model.MeioComunicacao.Telefones ?? listaBase;
            ViewBag.Celulares = model.MeioComunicacao.Celulares ?? listaBase;
            ViewBag.Emails = model.MeioComunicacao.Emalis ?? listaBase;

            return View(response.Data.ObjetoRetorno);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "EditarFornecedor")]
        public ActionResult EditarFornecedor(FornecedorModel model)
        {
            var response = ServiceRequest.Put<RetornoBase<object>>(model, "api/Fornecedor/EditarFornecedor");
            return ReturnResponse(response);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "ExcluirFornecedor")]
        public JsonResult ExcluirFornecedor(int codigoFornecedor)
        {
            var response = ServiceRequest.Delete<RetornoBase<object>>(new { codigoFornecedor = codigoFornecedor }, "api/Fornecedor/ExcluirFornecedor");
            return ReturnResponse(response);
        }

        private void CriarViewBags(string subTitle)
        {
            ViewBag.Title = Mensagens.Provider;
            ViewBag.SubTitle = subTitle;

            var listaBase = new List<LookupModel>();
            var response = ServiceRequest.Get<List<LookupModel>>("api/Pessoa/ObterListaEstado");
            if (response.Data.TemErros)
            {
                ModelState.AddModelError("Erro", response.Data.Mensagem);
                ViewBag.Estados = listaBase;
            }
            ViewBag.Estados = response.Data.ObjetoRetorno;
            response = ServiceRequest.Get<List<LookupModel>>("api/Pessoa/ObterListaEstadoCivil");
            if (response.Data.TemErros)
            {
                ModelState.AddModelError("Erro", response.Data.Mensagem);
                ViewBag.EstadosCivis = listaBase;
            }
            ViewBag.EstadosCivis = response.Data.ObjetoRetorno;
        }
    }
}

ProjetoArtCouro/ProjetoArtCouro.Web/Controllers/Usuarios/UsuarioController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using ProjetoArtCouro.Model.Models.Common;
using ProjetoArtCouro.Model.Models.Usuario;
using ProjetoArtCouro.Resources.Resources;
using ProjetoArtCouro.Web.Infra.Authorization;
using ProjetoArtCouro.Web.Infra.Service;
namespace ProjetoArtCouro.Web.Controllers.Usuarios
{
    public class UsuarioController : BaseController
    {
        [CustomAuthorize(Roles = "PesquisaUsuario")]
        public ActionResult PesquisaUsuario()
        {
            CriarViewBags(Mensagens.SearchUser);
            return View();
        }

        [HttpPost]
        [CustomAuthorize(Roles = "PesquisaUsuario")]
        public JsonResult PesquisaUsuario(PesquisaUsuarioModel model)
        {
            var response = ServiceRequest.Post<List<UsuarioModel>>(model, "api/Usuario/PesquisarUsuario");
            if (response.Data.ObjetoRetorno != null && !response.Data.ObjetoRetorno.Any())
            {
                response.Data.Mensagem = Erros.NoUsersForTheGivenFilter;
            }
            return ReturnResponse(response);
        }

        [CustomAuthorize(Roles = "NovoUsuario")]
        public ActionResult NovoUsuario()
        {
            CriarViewBags(Mensagens.NewUser);
            return View();
        }

        [HttpPost]
        [CustomAuthorize(Roles = "NovoUsuario")]
        public JsonResult NovoUsuario(UsuarioModel model)
        {
            var response = ServiceRequest.Post<RetornoBase<object>>(model, "api/Usuario/CriarUsuario");
            return ReturnResponse(response);
        }

        [CustomAuthorize(Roles = "EditarUsuario")]
        public ActionResult EditarUsuario(int codigoUsuario)
        {
            CriarViewBags(Mensagens.EditUser);
            var response = ServiceRequest.Post<UsuarioModel>(new { codigoUsuario = codigoUsuario }, "api/Usuario/PesquisarUsuarioPorCodigo");
            return View(response.Data.ObjetoRetorno);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "EditarUsuario")]
        public JsonResult EditarUsuario(UsuarioModel model)
        {
            var response = ServiceRequest.Put<UsuarioModel>(model, "api/Usuario/EditarUsuario");
            return ReturnResponse(response);
        }

        [CustomAuthorize(Roles = "AlterarSenha")]
        public ActionResult AlterarSenha()
        {
            ViewBag.Title = Mensagens.User;
            ViewBag.SubTitle = Mensagens.ChangePassword;
            return View();
        }

        [HttpPost]
        [CustomAuthorize(Roles = "AlterarSenha")]
        public JsonResult AlterarSenha(UsuarioModel model)
        {
            var response = ServiceRequest.Put<UsuarioModel>(model, "api/Usuario/AlterarSenha");
            return ReturnResponse(response);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "ExcluirUsuario")]
        public JsonResult ExcluirUsuario(int codigoUsuario)
        {
            var response = ServiceRequest.Delete<RetornoBase<object>>(new { codigoUsuario = codigoUsuario }, "api/Usuario/ExcluirUsuario");
            return ReturnResponse(response);
        }

        private void CriarViewBags(string subTitulo)
        {
            var response = ServiceRequest.Get<List<GrupoModel>>("api/Usuario/ObterListaGrupo");
            ViewBag.Grupos = response.Data.ObjetoRetorno;
            ViewBag.Title = Mensagens.User;
            ViewBag.SubTitle = subTitulo;
        }
    }
}

ProjetoArtCouro/ProjetoArtCouro.Web/Views/Shared/Authorize.cshtml
<section id="content-authorize" class="animate-fade-up">
    <div class="page-err">
        <div class="text-center">
            <div class="err-status">
                <h1>403</h1>
            </div>
            <div class="err-message">
                <h2>Acesso não autorizado.</h2>
            </div>
            <div class="err-body">
                <a href="/" class="btn btn-lg btn-goback">
                    <span class="fa fa-lg fa-fw fa-home"></span>
                    <span class="space"></span>
                    Voltar para Home
                </a>
            </div>
        </div>
    </div>
</section>

ProjetoArtCouro/ProjetoArtCouro.Web/Views/Shared/_Endereco.cshtml
@model  ProjetoArtCouro.Model.Models.Common.PessoaModel
@using ProjetoArtCouro.Resources.Resources
@using ProjetoArtCouro.Web.Infra.Extensions

<fieldset>
    <div class="row">
        <section class="col col-xs-12 col-sm-6 col-md-6 col-lg-6">
            @Html.LabelFor(m => m.Endereco.EnderecoId, new { @class = "label" })
            <label class="select">
                @Html.DropDownListFor(m => m.Endereco.EnderecoId, new SelectList(ViewBag.Enderecos, "Codigo", "Nome")
                         .AddDefaultOption(Mensagens.Select)
                         .AddDefaultLastOption(Mensagens.New, "0")
                         , new { placeholder = @Mensagens.Code })
                <i></i>
            </label>
            @Html.ValidationMessageFor(m => m.Endereco.EnderecoId)
        </section>
    </div>
    <div class="row NovoEndereco">
        <section class="col col-xs-12 col-sm-8 col-md-8 col-lg-8">
            @Html.LabelFor(m => m.Endereco.Logradouro, new {@class = "label"})
            <label class="input">
                @Html.TextBoxFor(m => m.Endereco.Logradouro, new {placeholder = @Mensagens.Patio, MaxLength = "100"})
            </label>
            @Html.ValidationMessageFor(m => m.Endereco.Logradouro)
        </section>
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4">
            @Html.LabelFor(m => m.Endereco.Numero, new { @class = "label" })
            <label class="input">
                @Html.TextBoxFor(m => m.Endereco.Numero, new { placeholder = @Mensagens.Number, MaxLength = "6" })
            </label>
            @Html.ValidationMessageFor(m => m.Endereco.Numero)
        </section>
    </div>
    <div class="row NovoEndereco">
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4">
            @Html.LabelFor(m => m.Endereco.Bairro, new {@class = "label"})
            <label class="input">
                @Html.TextBoxFor(m => m.Endereco.Bairro, new {placeholder = @Mensagens.Neighborhood, MaxLength = "50"})
            </label>
            @Html.ValidationMessageFor(m => m.Endereco.Bairro)
        </section>
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4">
            @Html.LabelFor(m => m.Endereco.Complemento, new {@class = "label"})
            <label class="input">
                @Html.TextBoxFor(m => m.Endereco.Complemento, new {placeholder = @Mensagens.Complement, MaxLength = "30"})
            </label>
            @Html.ValidationMessageFor(m => m.Endereco.Complemento)
        </section>
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4">
            @Html.LabelFor(m => m.Endereco.Cidade, new {@class = "label"})
            <label class="input">
                @Html.TextBoxFor(m => m.Endereco.Cidade, new { placeholder = @Mensagens.City, @class = "SomenteCinquentaLetras" })
            </label>
            @Html.ValidationMessageFor(m => m.Endereco.Cidade)
        </section>
    </div>
    <div class="row NovoEndereco">
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4">
            @Html.LabelFor(m => m.Endereco.Cep, new { @class = "label" })
            <label class="input">
                @Html.TextBoxFor(m => m.Endereco.Cep, new { placeholder = @Mensagens.CEP, MaxLength = "9", @class = "CepMask" })
            </label>
            @Html.ValidationMessageFor(m => m.Endereco.Cep)
        </section>
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4">
            @Html.LabelFor(m => m.Endereco.UFId, new { @class = "label" })
            <label class="select">
                @Html.DropDownListFor(m => m.Endereco.UFId, new SelectList(ViewBag.Estados, "Codigo", "Nome")
                    .AddDefaultOption(Mensagens.Select))
                <i></i>
            </label>
            @Html.ValidationMessageFor(m => m.Endereco.UFId)
        </section>
    </div>
</fieldset>

ProjetoArtCouro/ProjetoArtCouro.Web/Views/Shared/_MeioComunicacao.cshtml
@model  ProjetoArtCouro.Model.Models.Common.PessoaModel
@using ProjetoArtCouro.Resources.Resources
@using ProjetoArtCouro.Web.Infra.Extensions

<fieldset>
    <div class="row">
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4">
            @Html.LabelFor(m => m.MeioComunicacao.TelefoneId, new { @class = "label" })
            <label class="select">
                @Html.DropDownListFor(m => m.MeioComunicacao.TelefoneId, new SelectList(ViewBag.Telefones, "Codigo", "Nome")
                         .AddDefaultOption(Mensagens.Select)
                         .AddDefaultLastOption(Mensagens.New, "0"))
                <i></i>
            </label>
            @Html.ValidationMessageFor(m => m.MeioComunicacao.TelefoneId)
        </section>
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4">
            @Html.LabelFor(m => m.MeioComunicacao.CelularId, new { @class = "label" })
            <label class="select">
                @Html.DropDownListFor(m => m.MeioComunicacao.CelularId, new SelectList(ViewBag.Celulares, "Codigo", "Nome")
                         .AddDefaultOption(Mensagens.Select)
                         .AddDefaultLastOption(Mensagens.New, "0"))
                <i></i>
            </label>
            @Html.ValidationMessageFor(m => m.MeioComunicacao.CelularId)
        </section>
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4">
            @Html.LabelFor(m => m.MeioComunicacao.EmailId, new { @class = "label" })
            <label class="select">
                @Html.DropDownListFor(m => m.MeioComunicacao.EmailId, new SelectList(ViewBag.Emails, "Codigo", "Nome")
                         .AddDefaultOption(Mensagens.Select)
                         .AddDefaultLastOption(Mensagens.New, "0"))
                <i></i>
            </label>
            @Html.ValidationMessageFor(m => m.MeioComunicacao.EmailId)
        </section>
    </div>
    <div class="row">
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4 NovoTelefone">
            @Html.LabelFor(m => m.MeioComunicacao.Telefone, new { @class = "label" })
            <label class="input">
                @Html.TextBoxFor(m => m.MeioComunicacao.Telefone, new { placeholder = @Mensagens.NewPhone, @class = "TelefoneMask" })
            </label>
            @Html.ValidationMessageFor(m => m.MeioComunicacao.Telefone)
        </section>
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4 NovoCelular">
            @Html.LabelFor(m => m.MeioComunicacao.Celular, new { @class = "label" })
            <label class="input">
                @Html.TextBoxFor(m => m.MeioComunicacao.Celular, new { placeholder = @Mensagens.NewCellPhone, @class = "CelularMask" })
            </label>
            @Html.ValidationMessageFor(m => m.MeioComunicacao.Celular)
        </section>
        <section class="col col-xs-12 col-sm-4 col-md-4 col-lg-4 NovoEmail">
            @Html.LabelFor(m => m.MeioComunicacao.Email, new { @class = "label" })
            <label class="input">
                @Html.TextBoxFor(m => m.MeioComunicacao.Email, new { placeholder = @Mensagens.NewEmail, MaxLength = "50" })
            </label>
            @Html.ValidationMessageFor(m => m.MeioComunicacao.Email)
        </section>
    </div>
</fieldset>

ProjetoArtCouro/ProjetoArtCouro.Web/Views/Shared/_SideMenu.cshtml
@using ProjetoArtCouro.Resources.Resources

<aside id="left-panel">
    <div class="login-info">
        <span>
        </span>
    </div>
    <nav>
        <ul>
            <li>
                <a href="/" title="Home">
                    <i class="fa fa-lg fa-fw fa-home"></i>
                    <span class="menu-item-parent">@Mensagens.Home</span>
                </a>
            </li>
            <li>
                <a href="javascript:void(0)">
                    <i class="fa fa-lg fa-fw fa-pencil-square-o"></i>
                    <span class="menu-item-parent">@Mensagens.Register</span>
                </a>
                <ul>
                    <li>
                        <a href="javascript:void(0)">@Mensagens.Person</a>
                        <ul>
                            @if (User.IsInRole("PesquisaCliente"))
                            {
                                <li>
                                    @Html.ActionLink(Mensagens.Client, "PesquisaCliente", "Cliente")
                                </li>
                            }
                            @if (User.IsInRole("PesquisaFornecedor"))
                            {
                                <li>
                                    @Html.ActionLink(Mensagens.Provider, "PesquisaFornecedor", "Fornecedor")
                                </li>
                            }
                            @if (User.IsInRole("PesquisaFuncionario"))
                            {
                                <li>
                                    @Html.ActionLink(Mensagens.Employee, "PesquisaFuncionario", "Funcionario")
                                </li>
                            }
                        </ul>
                    </li>
                    @if (User.IsInRole("PesquisaProduto"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.Product, "PesquisaProduto", "Produto")
                        </li>
                    }
                    @if (User.IsInRole("PesquisaFormaPagamento"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.FormOfPayment, "PesquisaFormaPagamento", "FormaPagamento")
                        </li>
                    }
                    @if (User.IsInRole("PesquisaCondicaoPagamento"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.PaymentTerms, "PesquisaCondicaoPagamento", "CondicaoPagamento")
                        </li>
                    }
                    @if (User.IsInRole("PesquisaUsuario"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.Users, "PesquisaUsuario", "Usuario")
                        </li>
                    }
                </ul>
            </li>
            <li>
                <a href="javascript:void(0)">
                    <i class="fa fa-lg fa-fw fa-table"></i>
                    <span class="menu-item-parent">@Mensagens.Operations</span>
                </a>
                <ul>
                    @if (User.IsInRole("PesquisaCompra"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.Buy, "PesquisaCompra", "Compra")
                        </li>
                    }
                    @if (User.IsInRole("PesquisaVenda"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.Sale, "PesquisaVenda", "Venda")
                        </li>
                    }
                    @if (User.IsInRole("PesquisaContaPagar"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.AccountsPayable, "PesquisaContaPagar", "ContaPagar")
                        </li>
                    }
                    @if (User.IsInRole("PesquisaContaReceber"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.AccountsReceivable, "PesquisaContaReceber", "ContaReceber")
                        </li>
                    }
                </ul>
            </li>
            <li>
                <a href="javascript:void(0)">
                    <i class="fa fa-lg fa-fw fa-bar-chart-o"></i>
                    <span class="menu-item-parent">@Mensagens.Report</span>
                </a>
                <ul>
                    <li>
                        @Html.ActionLink(Mensagens.Stock, "PesquisaEstoque", "Estoque")
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:void(0)">
                    <i class="fa fa-lg fa-fw fa-cogs"></i>
                    <span class="menu-item-parent">@Mensagens.Settings</span>
                </a>
                <ul>
                    @if (User.IsInRole("PesquisaGrupo"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.GroupSettings, "PesquisaGrupo", "Configuracao")
                        </li>
                    }
                    @if (User.IsInRole("ConfiguracaoUsuario"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.SettingsForUsers, "ConfiguracaoUsuario", "Configuracao")
                        </li>
                    }
                    @if (User.IsInRole("AlterarSenha"))
                    {
                        <li>
                            @Html.ActionLink(Mensagens.ChangePassword, "AlterarSenha", "Usuario")
                        </li>
                    }
                </ul>
            </li>
        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu"><i class="fa fa-arrow-circle-left hit"></i></span>
</aside>