ProjetoArtCouro/ProjetoArtCouro.Web/Controllers/CondicoesPagamento/CondicaoPagamentoController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using ProjetoArtCouro.Model.Models.CondicaoPagamento;
using ProjetoArtCouro.Web.Infra.Authorization;
using ProjetoArtCouro.Web.Infra.Service;

namespace ProjetoArtCouro.Web.Controllers.CondicoesPagamento
{
    public class CondicaoPagamentoController : BaseController
    {
        [CustomAuthorize(Roles = "PesquisaCondicaoPagamento")]
        public ActionResult PesquisaCondicaoPagamento()
        {
            return View();
        }

        [CustomAuthorize(Roles = "PesquisaCondicaoPagamento")]
        public JsonResult ObterListaCondicaoPagamento()
        {
            var response = ServiceRequest.Get<List<CondicaoPagamentoModel>>("api/CondicaoPagamento/ObterListaCondicaoPagamento");
            return ReturnResponse(response);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "NovaCondicaoPagamento")]
        public JsonResult NovaCondicaoPagamento(CondicaoPagamentoModel model)
        {
            var response = ServiceRequest.Post<CondicaoPagamentoModel>(model, "api/CondicaoPagamento/CriarCondicaoPagamento");
            return ReturnResponse(response);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "EditarCondicaoPagamento")]
        public JsonResult EditarCondicaoPagamento(CondicaoPagamentoModel model)
        {
            var response = ServiceRequest.Put<object>(model, "api/CondicaoPagamento/EditarCondicaoPagamento");
            return ReturnResponse(response);
        }

        [HttpPost]
        [CustomAuthorize(Roles = "ExcluirCondicaoPagamento")]
        public JsonResult ExcluirCondicaoPagamento(int codigoCondicaoPagamento)
        {
            var response = ServiceRequest.Delete<object>(new { codigoCondicaoPagamento = codigoCondicaoPagamento },
                "api/CondicaoPagamento/ExcluirCondicaoPagamento");
            return ReturnResponse(response);
        }
    }
}

ProjetoArtCouro/ProjetoArtCouro.Web/Views/CondicaoPagamento/Index.cshtml
@model ProjetoArtCouro.Model.Models.CondicaoPagamento.CondicaoPagamento
@using ProjetoArtCouro.Resource.Resources


<div class="jarviswidget jarviswidget-sortable"
     data-widget-editbutton="true" data-widget-colorbutton="true"
     data-widget-fullscreenbutton="true" data-widget-collapsed="true"
     data-widget-custombutton="true" data-widget-togglebutton="true"
     data-widget-sortable="true" data-widget-deletebutton="true" role="widget" style="">
    <header role="heading">
        <span class="widget-icon"><i class="fa fa-edit"></i></span>
        <h2>@Mensagens.PaymentTerms </h2>
        <span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>
    </header>
    <div role="content">
        <div id="AlertaMensagens" class="col-xs-12 col-sm-12 col-md-12 col-lg-12 no-padding"></div>
        <div class="widget-body no-padding">
            <form id="formCondicaoPagamento" class="smart-form" novalidate="novalidate">
                <fieldset class="col col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="row">
                        <section class="col col-xs-12 col-sm-6 col-md-6 col-lg-6">
                            @Html.LabelFor(m => m.Descricao, new { @class = "label" })
                            <label class="input">
                                @Html.TextBoxFor(m => m.Descricao, new { placeholder = @Mensagens.Description })
                            </label>
                        </section>
                        <section class="col col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            @Html.LabelFor(m => m.QuantidadeParcelas, new { @class = "label" })
                            <label class="input">
                                @Html.TextBoxFor(m => m.QuantidadeParcelas, new { placeholder = @Mensagens.QuantityOfParcels })
                            </label>
                        </section>
                        <section class="col col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            @Html.LabelFor(m => m.Ativo, new { @class = "label" })
                            <div class="inline-group">
                                <label class="radio">
                                    @Html.RadioButtonFor(m => m.Ativo, true, new { data_text = @Mensagens.Yes })
                                    <i></i>@Mensagens.Yes
                                </label>
                                <label class="radio">
                                    @Html.RadioButtonFor(m => m.Ativo, false, new { data_text = @Mensagens.Not })
                                    <i></i>@Mensagens.Not
                                </label>
                            </div>
                        </section>
                    </div>
                    @Html.Hidden("LinhaCorrente")
                </fieldset>
                <footer>
                    <a id="AdicionarCondicaoPagamento" class="btn btn-primary" href="javascript:void(0);">
                        <i class="fa fa-floppy-o"></i> @Mensagens.Save
                    </a>
                </footer>
            </form>
            <fieldset class="col col-xs-12 col-sm-12 col-md-12 col-lg-12 WidgetCondicaoPagamento">
                <div class="jarviswidget jarviswidget-color-blueDark" data-widget-fullscreenbutton="false"
                     data-widget-colorbutton="false" data-widget-togglebutton="false"
                     data-widget-deletebutton="false" data-widget-editbutton="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                        <h2>Tabela de Condições de Pagamento</h2>
                    </header>
                    <div>
                        <div class="widget-body no-padding">
                            <table id="datatableCondicaoPagamento" class="table table-striped table-bordered table-hover" width="100%"></table>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/js/app/Search.js"></script>
    <script>
        Portal.Mask();
        Portal.Form({
            Button: $("#Salvar"),
            Form: $("#smart-form-register")
        });
        Portal.TabelaDinamica({
            AlertaMensagensSeletor: "#AlertaMensagens",
            AdicionaLinhaSeletor: "#AdicionarCondicaoPagamento",
            TabelaSeletor: "#datatableCondicaoPagamento",
            TituloRodape: "Condição de Pagamento",
            TituloRodapeContador: "Nenhuma condição de pagamento",
            InformacaoTabela: "Adicione novas condição de pagamento",
            BotaoEditarSeletor: ".EditarCondicaoPagamento",
            BotaoExcluirSeletor: ".ExcluirCondicaoPagamento",
            LinhaCorrenteSeletor: "#LinhaCorrente",
            Codigo: 0,
            OrdenacaoDoCabecalho: [
                { "sTitle": "@(Mensagens.Code)", "mData": "Codigo", "sClass": "center", "sWidth": "10%" },
                { "sTitle": "@(Mensagens.Description)", "mData": "Descricao", "sClass": "center", "sWidth": "40%" },
                { "sTitle": "@(Mensagens.QuantityOfParcels)", "mData": "QuantidadeParcelas", "sClass": "center", "sWidth": "15%" },
                { "sTitle": "@(Mensagens.Active)", "mData": "Ativo", "sClass": "center", "sWidth": "15%" },
                {
                    "sTitle": "@(Mensagens.Actions )",
                    "mData": null,
                    "sClass": "center",
                    "sWidth": "10%",
                    "bSortable": false,
                    "mRender": function () {
                        return "<div class=\"editable-buttons\">" +
                            "<button type=\"button\" class=\"btn btn-success btn-sm EditarCondicaoPagamento\" title=\"Editar\">" +
                            "<i class=\"fa fa-lg fa-pencil-square-o\"></i>" +
                            "<button type=\"button\" class=\"btn btn-danger btn-sm ExcluirCondicaoPagamento\" title=\"Deletar\">" +
                            "<i class=\"fa fa-lg fa-trash-o\"></i>" +
                            "</button>" +
                            "</div>";
                    }
                }
            ],
            ObterCampos: function (codigo) {
                var item = [
                    {
                        "Codigo": codigo,
                        "Descricao": $("#Descricao").val(),
                        "QuantidadeParcelas": $("#QuantidadeParcelas").val(),
                        "Ativo": $("#Ativo").closest(".inline-group").find(":checked").attr("data-text")
                    }
                ];
                $("#Descricao").val("");
                $("#Ativo").closest(".inline-group").find(":checked")[0].checked = false;
                $("#QuantidadeParcelas").val("");
                return item;
            },
            PreencherCampos: function (obj) {
                $("#Descricao").val(obj["Descricao"]);
                $("#Ativo").closest(".inline-group").find(":contains(" + obj["Ativo"] + ")").find("input")[0].checked = true;
                $("#QuantidadeParcelas").val(obj["QuantidadeParcelas"]);
            }
        });
    </script>
}

ProjetoArtCouro/ProjetoArtCouro.Web/Views/CondicaoPagamento/PesquisaCondicaoPagamento.cshtml
@model ProjetoArtCouro.Model.Models.CondicaoPagamento.CondicaoPagamentoModel
@using ProjetoArtCouro.Resources.Resources


<div class="jarviswidget jarviswidget-sortable"
     data-widget-editbutton="true" data-widget-colorbutton="true"
     data-widget-fullscreenbutton="true" data-widget-collapsed="true"
     data-widget-custombutton="true" data-widget-togglebutton="true"
     data-widget-sortable="true" data-widget-deletebutton="true" role="widget" style="">
    <header role="heading">
        <span class="widget-icon"><i class="fa fa-edit"></i></span>
        <h2>@Mensagens.PaymentTerms </h2>
        <span class="jarviswidget-loader"><i class="fa fa-refresh fa-spin"></i></span>
    </header>
    <div role="content">
        <div class="widget-body no-padding">
            <form id="formCondicaoPagamento" class="smart-form" novalidate="novalidate">
                <fieldset>
                    <div class="row">
                        <section id="AlertaMensagens" class="col col-xs-12 col-sm-12 col-md-12 col-lg-12 no-margin"></section>
                    </div>
                    <div class="row">
                        <section class="col col-xs-12 col-sm-6 col-md-6 col-lg-6">
                            @Html.LabelFor(m => m.Descricao, new {@class = "label"})
                            <label class="input">
                                @Html.TextBoxFor(m => m.Descricao, new {placeholder = @Mensagens.Description, maxlength = 50})
                            </label>
                            @Html.ValidationMessageFor(m => m.Descricao)
                        </section>
                        <section class="col col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            @Html.LabelFor(m => m.QuantidadeParcelas, new {@class = "label"})
                            <label class="input">
                                @Html.TextBoxFor(m => m.QuantidadeParcelas, new {placeholder = @Mensagens.QuantityOfParcels, @class = "SomenteDoisDigitos"})
                            </label>
                            @Html.ValidationMessageFor(m => m.QuantidadeParcelas)
                        </section>
                        <section class="col col-xs-12 col-sm-3 col-md-3 col-lg-3">
                            @Html.LabelFor(m => m.Ativo, new {@class = "label"})
                            <div class="inline-group">
                                <label class="radio">
                                    @Html.RadioButtonFor(m => m.Ativo, true, new {data_text = @Mensagens.Yes})
                                    <i></i>@Mensagens.Yes
                                </label>
                                <label class="radio">
                                    @Html.RadioButtonFor(m => m.Ativo, false, new {data_text = @Mensagens.Not})
                                    <i></i>@Mensagens.Not
                                </label>
                            </div>
                            @Html.ValidationMessageFor(m => m.Ativo)
                        </section>
                    </div>
                </fieldset>
                <footer>
                    <a id="AdicionarCondicaoPagamento" class="btn btn-labeled btn-primary" href="javascript:void(0);">
                        <span class="btn-label"><i class="fa fa-plus"></i></span> @Mensagens.Add
                    </a>
                </footer>
            </form>
        </div>
    </div>
</div>
<fieldset class="WidgetCondicaoPagamento ScrollWidgetTable">
    <div class="jarviswidget jarviswidget-color-blueDark" data-widget-fullscreenbutton="false"
         data-widget-colorbutton="false" data-widget-togglebutton="false"
         data-widget-deletebutton="false" data-widget-editbutton="false">
        <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>Tabela de Condições de Pagamento</h2>
        </header>
        <div class="ScrollTableContent">
            <div class="widget-body no-padding">
                <table id="datatableCondicaoPagamento" class="table table-striped table-bordered table-hover" width="100%"></table>
            </div>
        </div>
    </div>
</fieldset>

@section Scripts{
    <script src="~/js/app/Search.js"></script>
    <script>
        Portal.Mask();
        Portal.Form({
            Button: $("#Salvar"),
            Form: $("#smart-form-register")
        });
        Portal.TabelaDinamica({
            AdicionaLinhaSeletor: "#AdicionarCondicaoPagamento",
            TabelaSeletor: "#datatableCondicaoPagamento",
            TituloRodape: "Condição de Pagamento",
            TituloRodapeContador: "Nenhuma condição de pagamento",
            InformacaoTabela: "Adicione novas condição de pagamento",
            BotaoEditarSeletor: ".EditarCondicaoPagamento",
            BotaoExcluirSeletor: ".ExcluirCondicaoPagamento",
            $Formulario: $("#formCondicaoPagamento"),
            UrlLista: "@Url.Action("ObterListaCondicaoPagamento", "CondicaoPagamento")",
            UrlCriar: "@Url.Action("NovaCondicaoPagamento", "CondicaoPagamento")",
            OrdenacaoDoCabecalho: [
                { "sTitle": "@(Mensagens.Code)", "mData": "CondicaoPagamentoCodigo", "sWidth": "10%" },
                { "sTitle": "@(Mensagens.Description)", "mData": "Descricao", "sWidth": "40%" },
                { "sTitle": "@(Mensagens.QuantityOfParcels)", "mData": "QuantidadeParcelas", "sWidth": "15%" },
                {
                    "sTitle": "@(Mensagens.Active)",
                    "mData": null,
                    "sWidth": "15%",
                    "mRender": function (obj) {
                        return obj.Ativo ? "Sim" : "Não";
                    }
                },
                {
                    "sTitle": "@(Mensagens.Actions)",
                    "mData": null,
                    "sClass": "center",
                    "sWidth": "10%",
                    "bSortable": false,
                    "mRender": function (obj) {
                        var settings = JSON.stringify({
                            "objetoAdicional": { "name": "CondicaoPagamentoCodigo", "value": obj.CondicaoPagamentoCodigo },
                            "objetoExcluir": { "codigoCondicaoPagamento": obj.CondicaoPagamentoCodigo },
                            "urlEditar": "/CondicaoPagamento/EditarCondicaoPagamento",
                            "urlExcluir": "/CondicaoPagamento/ExcluirCondicaoPagamento",
                            "seletorTabela": "#datatableCondicaoPagamento",
                            "seletorBotaoModalAtualizar": "#AtualizarCondicaoPagamento",
                            "seletorFormulario": "#formModalCondicaoPagamento",
                            "seletorModal": "#modalCondicaoPagamento"
                        });
                        var botoes = Portal.CriarBotoesTabelaDinamica(
                            "Portal.EditarItemTabelaDinamica(this, " + settings + ")",
                            "Portal.ExcluirItemTabelaDinamica(this, " + settings + ")",
                            "#modalCondicaoPagamento");
                        return botoes[0].outerHTML;
                    }
                }
            ]
        });
        Portal.LimparCampos = function () {
            $("#Descricao").val("");
            $("#Ativo").closest(".inline-group").find(":checked")[0].checked = false;
            $("#QuantidadeParcelas").val("");
        }
        Portal.PreencherCamposModal = function (obj) {
            $("#ModalCondicaoPagamentoDescricao").val(obj["Descricao"]);
            $("#ModalCondicaoPagamentoAtivo").closest(".inline-group").find("input[value=" + obj["Ativo"].toString().capitalize() + "]")[0].checked = true;
            $("#ModalCondicaoPagamentoQuantidadeParcelas").val(obj["QuantidadeParcelas"]);
        }
    </script>
}